---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpc-aws
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: demovpc.com/v1alpha1
    kind: CompositeVpc
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
  - name: vpc-aws
    base:
      apiVersion: ec2.aws.crossplane.io/v1beta1
      kind: VPC
      metadata:
        name: demovpc
      spec:
        forProvider:
          region: us-east-1
          enableDnsSupport: true
          enableDnsHostNames: true
          tags:
          - key: Name
            value: demovpc
          instanceTenancy: default
        providerConfigRef:
          name: awsconfig
    patches:
    - fromFieldPath: spec.parameters.vpcCidr
      toFieldPath: spec.forProvider.cidrBlock	  
  - name: subnet-aws
    base:
      apiVersion: ec2.aws.crossplane.io/v1beta1
      kind: Subnet
      metadata:
        name: demo-subnet
      spec:
        forProvider:
          region: us-east-1
          availabilityZone: us-east-1a
          vpcIdSelector:
            matchControllerRef: true
          tags:
          - key: Name
            value: demo-subnet
          mapPublicIPOnLaunch: true
        providerConfigRef:
          name: awsconfig
    patches:
    - fromFieldPath: spec.parameters.subnetCidr
      toFieldPath: spec.forProvider.cidrBlock
  - name: InternetGateway
    base:
      apiVersion: ec2.aws.crossplane.io/v1beta1
      kind: InternetGateway
      metadata:
        name: demo-internetgateway
      spec:
        forProvider:
          region: us-east-1
          vpcIdSelector:
            matchControllerRef: true            
        providerConfigRef:
          name: awsconfig
  - name: RouteTable
    base:
      apiVersion: ec2.aws.crossplane.io/v1beta1
      kind: RouteTable
      metadata:
        name: demo-routetable
      spec:
        forProvider:
          region: us-east-1
          routes:
            - destinationCidrBlock: 0.0.0.0/0
              gatewayIdSelector:
                matchControllerRef: true
          associations:
            - subnetIdSelector:
                matchControllerRef: true
          vpcIdSelector:
            matchControllerRef: true
        providerConfigRef:
          name: awsconfig
