---
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: production-rds
spec:
  forProvider:
    allocatedStorage: 50
    autoMinorVersionUpgrade: true
    applyModificationsImmediately: false
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t2.small
    dbSubnetGroupName: prod-subnet-group
    vpcSecurityGroupIDRefs:
      - name: rds-access-sg
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: mysql
    region: us-east-1
    engineVersion: 8.0.28
    finalDBSnapshotIdentifier: mysql-example-backup
    licenseModel: general-public-license
    masterUsername: admin
    multiAZ: true
    port: 3306
    tags:
    - key: Name
      value: production-rds
    publiclyAccessible: true
    storageEncrypted: false
    storageType: gp2
  providerConfigRef:
    name: awsconfig
  writeConnectionSecretToRef:
    name: production-rds-conn-string
    namespace: default
